stages:
  - lint
  - test
  - generate-template
  - cleanup
  - version
  - release

# Lint Stage
lint:
  stage: lint
  image: "python:3.12"
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

# Test Stage
test:
  stage: test
  image: "python:3.12"
  before_script:
    - pip install pytest cookiecutter
  script:
    - pytest tests

# Generate Template Stage
generate-template:
  stage: generate-template
  image: "python:3.12"
  before_script:
    - pip install poetry cookiecutter
  script:
    - cookiecutter . --no-input
    - cd mon_super_projet && poetry check

# Cleanup Stage
cleanup:
  stage: cleanup
  image: "alpine:latest"
  script:
    - echo "Cleaning up temporary generated project files."
    - rm -rf mon_super_projet

# Generate Changelog, Tag, and Increment Version
generate_changelog:
  stage: version
  image: "node:lts"
  before_script:
    # Installer jq au besoin
    - apt-get update -y && apt-get install jq -y
    # Configurer ssh-agent pour sécuriser les accès
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$CI_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    # Initialiser Git avec configuration de base
    - git init || true
    - git remote add origin "${CI_REPOSITORY_URL}" || echo 'Remote already exists.'
    - git remote add github git@github.com:stan-kempachi/cookiecutter-python-template.git || echo 'GitHub remote already exists.'
    - git fetch --all
    # Gérer les branches
    - |
      if [ "${CI_COMMIT_BRANCH}" != "" ]; then
        git checkout -b "${CI_COMMIT_BRANCH}" --track origin/"${CI_COMMIT_BRANCH}" || 
        git checkout "${CI_COMMIT_BRANCH}";
      else
        git checkout -b master --track origin/master || 
        git checkout master;
      fi
    # Configurer l'URL pour les remotes en utilisant SSH
    - git remote set-url origin git@gitlab.com:adm.standev/cookiecutter-python-template.git
    # Configurer git user.name et user.email
    - git config --global user.name "${GITLAB_USER_NAME:-ci-user}"
    - git config --global user.email "${GITLAB_USER_EMAIL:-ci-user@gitlab.com}"
  script:
    - npm install
    - npm audit fix || true
    # Vérifier la version dans package.json
    - |
      if ! jq -e '.version' package.json > /dev/null; then
        echo "Error: Version not defined in package.json";
        exit 1;
      fi
    - |
      if [ "$(jq -r '.version' package.json)" = "null" ]; then
        echo "Error: Version in package.json is null";
        exit 1;
      fi
    # Incrémentation et génération des tags
    - npx standard-version --release-as auto
    # Vérifier que la version est valide
    - |
      if grep '"version": null' package.json; then
        echo "Error: Invalid version generated by standard-version";
        git reset --hard;
        exit 1;
      fi
    # Ajouter et valider les modifications
    - git add package.json package-lock.json CHANGELOG.md
    - |
      VERSION=$(jq -r .version package.json)
      git commit -m "chore(release): $VERSION" || echo "No changes to commit"
    # Pousser les commits et les tags
    - git push origin --follow-tags # Vers GitLab
    - git push github --follow-tags # Vers GitHub
  rules:
    - if: $CI_COMMIT_TAG == null

# Release Stage
release:
  stage: release
  image: "node:lts"
  script:
    - echo "Deployment in progress..."
  rules:
    - if: $CI_COMMIT_TAG != null